#pragma once

#define DISPLAY_WIDTH_VIRTUAL_PIXELS 128
#define DISPLAY_HEIGHT_VIRTUAL_PIXELS 96
#define DISPLAY_BUF_SIZE ((DISPLAY_WIDTH_VIRTUAL_PIXELS * DISPLAY_HEIGHT_VIRTUAL_PIXELS) / 8)
#define PIXEL_SIZE 2
#define DISPLAY_WIDTH (DISPLAY_WIDTH_VIRTUAL_PIXELS * PIXEL_SIZE)
#define DISPLAY_HEIGHT (DISPLAY_HEIGHT_VIRTUAL_PIXELS * PIXEL_SIZE)
#define WINDOW_WIDTH DISPLAY_WIDTH
#define WINDOW_HEIGHT (2 * DISPLAY_HEIGHT)

#define BUTTON_WIDTH (28 * PIXEL_SIZE)
#define BUTTON_HEIGHT (22 * PIXEL_SIZE)
#define BUTTON_X_SPACING (3)
#define BUTTON_Y_SPACING (3)

#define SELECT_BUTTON_X ((DISPLAY_WIDTH / 2) - (BUTTON_WIDTH / 2))
#define SELECT_BUTTON_Y (DISPLAY_HEIGHT + ((WINDOW_HEIGHT - DISPLAY_HEIGHT) / 2) - (BUTTON_HEIGHT / 2))
#define UP_BUTTON_X SELECT_BUTTON_X
#define UP_BUTTON_Y (SELECT_BUTTON_Y - BUTTON_HEIGHT - BUTTON_Y_SPACING)
#define DOWN_BUTTON_X SELECT_BUTTON_X
#define DOWN_BUTTON_Y (SELECT_BUTTON_Y + BUTTON_HEIGHT + BUTTON_Y_SPACING)
#define LEFT_BUTTON_X (SELECT_BUTTON_X - BUTTON_WIDTH - BUTTON_X_SPACING)
#define LEFT_BUTTON_Y SELECT_BUTTON_Y
#define RIGHT_BUTTON_X (SELECT_BUTTON_X + BUTTON_WIDTH + BUTTON_X_SPACING)
#define RIGHT_BUTTON_Y SELECT_BUTTON_Y
#define POWER_BUTTON_X (LEFT_BUTTON_X - (BUTTON_WIDTH / 2))
#define POWER_BUTTON_Y (DOWN_BUTTON_Y + (BUTTON_HEIGHT / 2))
#define BACK_BUTTON_X POWER_BUTTON_X
#define BACK_BUTTON_Y (UP_BUTTON_Y - (BUTTON_HEIGHT / 2))
